### PR TITLE
Check that variable assignments only have a single incoming edge

### PR DESCRIPTION
**Pull request by maxqchen**
WIP still! Just want to make sure the logic is correct before I start writing
tests. Also is there a good Exception for this case? I just threw in RTE for it
to compile but I'm sure there's something better. Maybe something we catch and
use the list of strings to print a helpful error message?

issue #51

### CODE REVIEW

**Comment by lucaswoj** [comment]
Logic looks good. :ship: when checkstyle is satiated.

**Comment by lucaswoj** [comment]
We don't have a great system for custom exceptions yet. Just do whatever you think makes sense :+1: Someday we can go back and look for patterns to make them more consistent.

**Comment by mtrberzi** [comment]
I haven't forgotten -- I'll review this once the build passes.

**Comment by mtrberzi** [comment]
Looks good, go ahead for ship!

**Pull request merged**
